In [2]:
import numpy as np
%matplotlib notebook

# Matrix Review

Take the matricies:

$\bf{A} =
\begin{pmatrix}
2 & 4 & -7\\
3 & -3 & 0\\
1 & 7 & 5
\end{pmatrix},\;\;
\bf{B} =
\begin{pmatrix}
2 & 4\\
3 & -3\\
1 & 7
\end{pmatrix}, \;\;
\bf{C} =
\begin{pmatrix}
-1 & 1\\
1 & -1
\end{pmatrix}, \;\;
\bf{D} = 
\begin{pmatrix}
2 & 0\\
-3 & 6
\end{pmatrix}
$ 

Define the matricies as numpy arrays

In [5]:
A = np.array([[2,4,-7], [3,-3,0], [1,7,5]])
B = np.array([[2,4], [3,-3], [1,7]])
C = np.array([[-1,1], [1,-1]])
D = np.array([[2,0], [-3,6]])
print(A)
print("-------")
print(B)
print("-------")
print(C)
print("-------")
print(D)


[[ 2  4 -7]
 [ 3 -3  0]
 [ 1  7  5]]
-------
[[ 2  4]
 [ 3 -3]
 [ 1  7]]
-------
[[-1  1]
 [ 1 -1]]
-------
[[ 2  0]
 [-3  6]]


1. Multiply $\bf{A}$ by 2.5 

In [6]:
E = A*2.5
print(E)

[[  5.   10.  -17.5]
 [  7.5  -7.5   0. ]
 [  2.5  17.5  12.5]]


2. Evaluate the product of $\bf{C}\cdot\bf{A}$ 

Did you get an error? Do you know why? (Hint: look at the dimensions of the matrix)
- Got an error. the matrices are 2x2 and 3x3, so can't multiply need number of rows to match columns of other 

In [7]:
F = C*A

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

3. Evaluate the product of $\bf{C}\cdot\bf{D}$ and then $\bf{D}\cdot\bf{C}$. Do you get the same results? 
- different answers CD != DC

In [8]:
G = C*D
H = D*C
print(G)
print(H)

[[-2  0]
 [-3 -6]]
[[-2  0]
 [-3 -6]]


4. Find the transpose of $\bf{B}$

In [10]:
B_transpose = B.transpose()
print(B_transpose)

[[ 2  3  1]
 [ 4 -3  7]]


5. Add $\bf{C} + \bf{D}$

In [11]:
I = C + D
print(I)

[[ 1  1]
 [-2  5]]


6. Compute the determinate of $\bf{C}$

In [12]:
J = np.linalg.det(C)
print(J)

0.0


7. Compute the determinate of $\bf{A}$

In [14]:
K = np.linalg.det(A)
print(K)

-257.9999999999998
